version: "3.7"
services:
  traggo:
    image: traggo/server:latest
    restart: unless-stopped
    ports:
      - 3030:3030
    environment:
      TRAGGO_DEFAULT_USER_NAME: "user"
      TRAGGO_DEFAULT_USER_PASS: "password"
    volumes:
      - ./traggodata:/opt/traggo/data
